# Generated by Django 5.2.13 on 2026-04-23 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('day_number', models.PositiveSmallIntegerField()),
                ('off_duty_hours', models.FloatField(default=0)),
                ('sleeper_berth_hours', models.FloatField(default=0)),
                ('driving_hours', models.FloatField(default=0)),
                ('on_duty_not_driving_hours', models.FloatField(default=0)),
                ('timeline', models.JSONField(default=list)),
                ('total_miles', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='trips.trip')),
            ],
            options={
                'verbose_name': 'ELD Log',
                'verbose_name_plural': 'ELD Logs',
                'ordering': ['day_number'],
            },
        ),
    ]
