# Generated by Django 5.2.13 on 2026-04-23 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('estimated_total_hours', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('rest', '30-Min Rest Break'), ('sleeper', '10-Hour Sleeper Berth'), ('fuel', 'Fuel Stop')], max_length=20)),
                ('location_name', models.CharField(max_length=255)),
                ('arrival_hour', models.FloatField(help_text='Hours elapsed from trip start')),
                ('duration_hours', models.FloatField()),
                ('cumulative_drive_hours', models.FloatField()),
                ('cumulative_miles', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Stop',
                'verbose_name_plural': 'Trip Stops',
                'ordering': ['arrival_hour'],
            },
        ),
    ]
