# Generated by Django 5.2.13 on 2026-04-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='carrier_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='co_driver_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='main_office_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='shipper_and_commodity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_numbers',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='stop_type',
            field=models.CharField(choices=[('pre_trip', 'Pre-Trip Inspection'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('rest', '30-Min Off-Duty Break'), ('sleeper', '10-Hour Sleeper Berth'), ('fuel', 'Fuel Stop')], max_length=20),
        ),
    ]
